apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My standard workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
      - name: Dire bonjour
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "bonjour le monde"
